"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { ArrowDown, ArrowRight, BrainCircuit, CheckCircle2, Database, Dna, Eye, Menu, Send, Server, Sparkles, X } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const stats = [["24", "GPUs", "대규모 학습을 위한 가속 자원"], ["200 TB", "Storage", "연구 데이터를 위한 고속 스토리지"], ["100 GbE", "Network", "노드 간 초고속 연결"], ["3", "Layers", "연산·네트워크·스토리지 통합"]];
const useCases = [
  { icon: BrainCircuit, title: "AI / LLM", text: "대규모 언어모델 학습과 추론" }, { icon: Eye, title: "Computer Vision", text: "고해상도 영상 분석과 모델 개발" },
  { icon: Dna, title: "Bio AI", text: "생명과학 데이터 기반 AI 연구" }, { icon: Database, title: "Data Science", text: "대규모 데이터 분석과 실험" },
  { icon: Sparkles, title: "Deep Learning", text: "복잡한 신경망의 빠른 학습" }, { icon: Server, title: "Research Computing", text: "고성능 병렬 연산과 시뮬레이션" },
];
const faqs = [
  ["AI 가속기는 누가 사용할 수 있나요?", "한동대학교 소속 연구자와 학생을 중심으로 운영되며, 산학협력 및 공동연구 과제도 협의를 통해 이용할 수 있습니다."],
  ["GPU는 어떻게 신청하나요?", "이용 목적, 예상 기간, 필요한 GPU 규모를 작성해 신청하면 AI 혁신센터에서 검토 후 자원을 배정합니다."],
  ["B200과 RTX PRO 6000의 차이는 무엇인가요?", "B200은 대규모 AI 학습과 HPC에, RTX PRO 6000은 비전·생성형 AI·연구 워크로드에 적합합니다."],
  ["사용 기간은 어떻게 결정되나요?", "과제 규모, 자원 사용량, 전체 운영 현황을 함께 검토해 승인 단계에서 이용 기간을 확정합니다."],
  ["스토리지는 제공되나요?", "연구용 고속 스토리지가 제공됩니다. 용량과 보관 기간은 신청 내용에 따라 협의합니다."],
  ["문의는 어디로 하면 되나요?", "페이지 하단 문의 양식을 이용하면 AI 혁신센터 담당자에게 전달됩니다."],
];

function ComputeGraphic({ variant = "b200" }: { variant?: "b200" | "rtx" }) {
  const isB200 = variant === "b200";
  return <figure className={`compute-visual ${variant}`}><div className="equipment-halo" aria-hidden="true" /><Image className="equipment-image" src={isB200 ? "/b200.png" : "/pro6000.png"} width={1200} height={1200} sizes="(max-width: 720px) 90vw, 42vw" alt={isB200 ? "NVIDIA B200 GPU 시스템" : "NVIDIA RTX PRO 6000 그래픽 카드"} /><figcaption><span>{isB200 ? "NVIDIA B200" : "RTX PRO 6000"}</span><small>ACTUAL EQUIPMENT</small></figcaption></figure>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  useEffect(() => { const items = document.querySelectorAll<HTMLElement>("[data-reveal]"); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible")), { threshold: 0.15 }); items.forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, []);
  async function submitContact(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSending(true); const response = await fetch("/api/contact", { method: "POST", body: new FormData(event.currentTarget) }); setSending(false); if (response.ok) setSent(true); else alert("문의 전송에 실패했습니다. 잠시 후 다시 시도해 주세요."); }
  return <main>
    <header className="site-header"><a href="#top" className="brand" aria-label="한동대학교 AI 혁신센터 홈"><Image src="/hgu_logo.svg" width={145} height={40} alt="한동대학교" priority /><span><b>AI 혁신센터</b><small>AI ACCELERATOR</small></span></a><nav className={menuOpen ? "open" : ""} aria-label="주요 메뉴">{[["소개","#about"],["인프라","#infrastructure"],["이용방법","#access"],["이용요금","#pricing"],["FAQ","#faq"],["문의","#contact"]].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><a className="header-cta" href="#contact">이용 안내 <ArrowRight size={16} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="메뉴 열기">{menuOpen ? <X /> : <Menu />}</button></header>
    <section id="top" className="hero"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy" data-reveal><p className="eyebrow">HANDONG GLOBAL UNIVERSITY <span /> AI INNOVATION CENTER</p><h1>한동대학교<br /><em>AI Accelerator</em></h1><p className="hero-lead">연구와 교육을 위한<br />고성능 AI Computing Infrastructure</p><p className="hero-desc">한동대학교 AI 혁신센터가 운영하는 GPU 기반 AI 연구 인프라를 소개합니다.</p><div className="hero-actions"><a className="button primary" href="#infrastructure">인프라 살펴보기 <ArrowDown size={17} /></a><a className="button secondary" href="#access">이용 방법</a></div></div><div className="hero-system" aria-hidden="true"><div className="system-ring r1" /><div className="system-ring r2" /><div className="system-core">AI<small>ACCELERATOR</small></div>{["GPU 01","GPU 02","100 GbE","STORAGE"].map((x, i) => <span className={`node n${i+1}`} key={x}>{x}</span>)}</div><div className="scroll-cue"><span>SCROLL TO EXPLORE</span><i /></div></section>
    <section className="stats-section" id="about"><div className="section-kicker">INFRASTRUCTURE AT A GLANCE</div><div className="stats-grid">{stats.map(([value,label,desc], i) => <article key={label} data-reveal style={{ transitionDelay: `${i * 80}ms` }}><strong>{value}</strong><h3>{label}</h3><p>{desc}</p></article>)}</div></section>
    <section id="infrastructure" className="compute-section"><div className="section-heading" data-reveal><p className="section-kicker">COMPUTE INFRASTRUCTURE</p><h2>더 큰 연구를 가능하게 하는<br />강력한 AI 연산 환경</h2></div><div className="compute-row" data-reveal><div className="compute-copy"><span className="index">01 / PRIMARY COMPUTE</span><h3>NVIDIA B200</h3><p>대규모 AI 학습과 고성능 연산을 위한 핵심 GPU 환경입니다.</p><ul><li><b>8 GPUs</b><span>고밀도 병렬 연산</span></li><li><b>Large-scale AI Training</b><span>대규모 모델 학습</span></li><li><b>HPC · LLM · Deep Learning</b><span>연구 워크로드 최적화</span></li></ul></div><ComputeGraphic /></div><div className="compute-row reverse" data-reveal><div className="compute-copy"><span className="index">02 / RESEARCH COMPUTE</span><h3>RTX PRO 6000</h3><p>비전, 생성형 AI, 실험 중심 연구를 유연하게 지원합니다.</p><ul><li><b>16 GPUs</b><span>확장 가능한 연구 자원</span></li><li><b>96GB GPU Memory</b><span>대용량 모델과 데이터셋</span></li><li><b>AI · Vision · Research</b><span>다양한 연구 환경</span></li></ul></div><ComputeGraphic variant="rtx" /></div></section>
    <section className="layers-section"><div className="section-heading light" data-reveal><p className="section-kicker">BUILT FOR AI RESEARCH</p><h2>연산부터 데이터까지,<br />하나로 연결된 인프라</h2></div><div className="layer-layout"><p data-reveal>연구자는 복잡한 인프라를 직접 구성할 필요 없이, 통합된 환경에서 연구에 집중할 수 있습니다.</p><div className="layers" data-reveal>{[['04','AI Platform','연구 환경 · 스케줄링 · 관리'],['03','GPU Compute','B200 · RTX PRO 6000'],['02','High-Speed Network','100 GbE Interconnect'],['01','Research Storage','200 TB High-Speed Storage']].map(([n,title,text]) => <div className="layer" key={title}><span>{n}</span><strong>{title}</strong><small>{text}</small></div>)}</div></div></section>
    <section id="access" className="access-section"><div className="section-heading" data-reveal><p className="section-kicker">SIMPLE ACCESS</p><h2>복잡한 인프라 없이<br />필요한 GPU를 사용하세요.</h2></div><div className="steps">{[["01","이용 신청","연구 목적과 필요한 자원을 작성합니다."],["02","사용 승인","센터에서 과제와 자원 규모를 검토합니다."],["03","GPU 자원 할당","승인된 일정에 맞춰 환경을 제공합니다."],["04","AI 연구 및 연산","할당된 자원에서 연구를 시작합니다."]].map(([n,t,d],i)=><article key={n} data-reveal style={{transitionDelay:`${i*80}ms`}}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div>{i<3&&<ArrowRight aria-hidden="true" />}</article>)}</div></section>
    <section id="pricing" className="pricing-section"><div className="section-heading" data-reveal><p className="section-kicker">SERVICE PRICING</p><h2>이용 요금 안내</h2><p className="pricing-lead">이용 요금은 운영 정책 확정 후 공개됩니다. 아래 항목별 기준에 따라 투명하게 안내할 예정입니다.</p></div><div className="pricing-grid">{[["NVIDIA B200","GPU 시간 기준","GPU 수 × 이용 시간"],["RTX PRO 6000","GPU 시간 기준","GPU 수 × 이용 시간"],["Storage","용량·기간 기준","사용 용량 × 보관 기간"]].map(([title,unit,basis],i)=><article key={title} data-reveal style={{transitionDelay:`${i*80}ms`}}><div className="price-card-head"><span>{String(i+1).padStart(2,"0")}</span><b>요금 확정 예정</b></div><h3>{title}</h3><div className="price-placeholder"><strong>별도 공지</strong><small>/ {unit}</small></div><dl><div><dt>산정 기준</dt><dd>{basis}</dd></div><div><dt>할인 정책</dt><dd>교내·공동연구 기준 검토 중</dd></div></dl></article>)}</div><div className="refund-policy" data-reveal><div><p className="section-kicker">CANCELLATION & REFUND</p><h3>취소 및 환불 규정</h3><p>예약 변경과 환불 기준은 최종 이용 요금과 함께 확정하여 공지합니다.</p></div><ul><li><span>01</span><div><b>사용 전 취소</b><p>예약 시작 전 취소 시점에 따른 환불 기준을 적용할 예정입니다.</p></div></li><li><span>02</span><div><b>사용 시작 후 취소</b><p>실제 사용된 자원과 시간을 기준으로 정산하는 방안을 검토 중입니다.</p></div></li><li><span>03</span><div><b>센터 사유 중단</b><p>장비 장애 등 센터 사유로 이용이 중단된 경우 보상 또는 환불 기준을 마련할 예정입니다.</p></div></li></ul><p className="policy-note">※ 본 내용은 정책 수립을 위한 안내 틀이며, 확정 전에는 효력이 없습니다.</p></div></section>
    <section className="usecase-section"><div className="section-heading" data-reveal><p className="section-kicker">BUILT FOR RESEARCH</p><h2>아이디어가 연구가 되는 곳</h2></div><div className="usecase-grid">{useCases.map(({icon:Icon,title,text},i)=><article key={title} data-reveal style={{transitionDelay:`${i%3*70}ms`}}><Icon /><h3>{title}</h3><p>{text}</p><span>RESEARCH AREA</span></article>)}</div></section>
    <section className="official-section"><div className="official-mark" data-reveal><Image src="/hgu_logo.svg" width={230} height={64} alt="한동대학교" /></div><div data-reveal><p className="section-kicker">HANDONG GLOBAL UNIVERSITY</p><h2>한동대학교 AI 혁신센터가<br />직접 운영합니다.</h2><p className="official-desc">본 AI 가속기 인프라는 한동대학교의 AI 연구 및 교육 지원을 위해 구축·운영됩니다.</p><dl><div><dt>운영기관</dt><dd>한동대학교 AI 혁신센터</dd></div><div><dt>위치</dt><dd>한동대학교</dd></div><div><dt>지원분야</dt><dd>AI 연구 · 교육 · 산학협력</dd></div><div><dt>문의</dt><dd>AI 혁신센터</dd></div></dl></div></section>
    <section id="faq" className="faq-section"><div className="section-heading" data-reveal><p className="section-kicker">FREQUENTLY ASKED QUESTIONS</p><h2>자주 묻는 질문</h2></div><Accordion className="faq-list" data-reveal>{faqs.map(([q,a],i)=><AccordionItem value={`item-${i}`} key={q}><AccordionTrigger><span><b>{String(i+1).padStart(2,'0')}</b>{q}</span></AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
    <section id="contact" className="contact-section"><div className="contact-intro" data-reveal><p className="section-kicker">CONTACT THE CENTER</p><h2>AI 연구를<br />시작하세요.</h2><p>AI 가속기 이용 또는 인프라 관련 문의가 있다면 AI 혁신센터로 문의해 주세요.</p><div className="contact-note"><CheckCircle2 /><span>접수된 문의는 담당자가 확인 후 안내드립니다.</span></div></div><div className="contact-card" data-reveal>{sent ? <div className="success"><CheckCircle2 /><h3>문의가 접수되었습니다.</h3><p>내용을 확인한 뒤 입력하신 이메일로 답변드리겠습니다.</p><button className="button secondary" onClick={()=>setSent(false)}>새 문의 작성</button></div> : <form onSubmit={submitContact}><div className="form-row"><label>이름<input name="name" required placeholder="홍길동" /></label><label>소속<input name="organization" required placeholder="학과 또는 기관명" /></label></div><label>이메일<input name="email" type="email" required placeholder="name@example.com" /></label><label>문의 제목<input name="subject" required placeholder="문의 제목을 입력해 주세요" /></label><label>문의 내용<textarea name="message" required rows={6} placeholder="이용 목적과 필요한 자원을 알려주세요." /></label><button className="button primary submit" disabled={sending}>{sending ? "전송 중..." : "문의 보내기"}<Send size={17}/></button></form>}</div></section>
    <footer><div className="footer-top"><div className="footer-brand"><Image src="/hgu_logo.svg" width={180} height={50} alt="한동대학교" /><p>한동대학교 AI 혁신센터</p></div><address>경상북도 포항시 북구 흥해읍 한동로 558</address><div className="footer-links"><a href="#contact">AI 가속기 문의</a><a href="https://www.handong.edu" target="_blank" rel="noreferrer">한동대학교 홈페이지</a><a href="https://www.handong.edu/kor/etc/privacy/" target="_blank" rel="noreferrer">개인정보처리방침</a></div></div><div className="footer-bottom">© HANDONG GLOBAL UNIVERSITY. All rights reserved.<span>AI INNOVATION CENTER · AI ACCELERATOR</span></div></footer>
  </main>;
}
